# Generated by Django 2.2 on 2020-10-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cisco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_id', models.CharField(max_length=32, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('loopback', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
